### ISSUE TITLE
Does this implementation allow MDM and Intune?

### ISSUE THREAD

**Issue by hodgesd** [acran/teams-in-docker#2]

**Comment by acran** [comment]
@hodgesd what features exactly are you expecting?

I did not test them and would suggest to just try it. But this is using the official Microsoft Teams for Linux client, so first of all this depends on whether Microsoft supports this on Linux.
Then you have to consider that Teams will be running inside a container and thus won't have access/affect the underlying host Linux system.

**Comment by hodgesd** [comment]
Didnt seem to work for me.  

I thought I'd try to install my company's MDM software in a container and prevent it from monitoring my host computer.  No luck.

Thanks.
