### ISSUE TITLE
Islolation and security

### ISSUE THREAD

**Issue by nuschpl** [acran/teams-in-docker#8]
There is no real value added running teams within docker container when docker is run as root or when teams is run outside the container itself. The real value added would be when keeping Microsoft spyware away from Linux host and every single file/device not needed for Teams to work. Is there a way to assure complete isolation ?

**Comment by acran** [comment]
The container setup is done by [`x11docker`](https://github.com/mviereck/x11docker) which does a pretty good job at providing only really necessary access to the host resources and locking down everything else as much as possible.

Therefor the `teams` process running in the container has only access to
* its own, isolated filesystem, only sharing `~/x11docker/teams` with the host
* no devices except for the camera (see the `--webcam` flag), audio input/output (through `pulseaudio`)
* and is running with the same - non-root - UID as the host user

You can modify the flags provided to `x11docker` in `teams.sh` to further restrict access:

https://github.com/acran/teams-in-docker/blob/5e4bf9e4176c3c51e8b538a99ee0502bc7660ec1/teams.sh#L22

But any further restrictions then of course cause loss of certain features in `teams`.
